version: '2'
services:
    jobsdetails-app:
        image: jobsdetails
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jobsdetails-mysql:3306/jobsdetails?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jobsdetails-mysql:
        extends:
            file: mysql.yml
            service: jobsdetails-mysql
